# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6563e8e3b79f136434b6fecb6493af889edd9bf0a17b712d5f2b1900ef34f27c730179c2b0e760d0000603642c316adcc07e007134410b08bd814b73427b67be

test:
  secret_key_base: 199055fbcff100e5dfeb1c6240091a205e80756d29ce7fb0c6dc0d64a16a56bc67b476120e5f3e4d8eeff238e5c12bcbf8be2243cbb958d950162326d984fb30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
